apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "8080"
    spec:
      containers:
        - name: api
          image: australia-southeast1-docker.pkg.dev/mimi-460207/demo-repo/api:v1   
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/mydb
          ports:
            - containerPort: 8080
